### ISSUE TITLE
Latest feren ppa's have broken themes

### ISSUE THREAD

**Issue by mrirvs1965** [feren-OS/feren-OS-Bug-Reporting#52]
Since the latest feren ppa's were updated (15/5/2018 for me) I am no longer able to open the themes within the system settings. Prior to this there were no issues.

.xsession_errors:

Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 555, in button_press
    self.side_view_nav(widget, None, category)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 116, in side_view_nav
    self.go_to_sidepage(cat, filtered_path)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 130, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 123, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 49, in on_module_selected
    self.sidePage.stack.add_titled(page, "themes", _("Themes"))
UnboundLocalError: local variable 'page' referenced before assignment

**Comment by feren** [comment]
Early Bird or Not Early Bird?

**Comment by feren** [comment]
@mrirvs1965 Stable: Just pushed a hopefully fixing update for feren-themer, as that package is what supplies the troublesome file in the error

**Comment by mrirvs1965** [comment]
Good job - works perfectly
